apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Fragment
metadata:
  name: spring-boot-mysql
  namespace: accelerator-system
spec:
  git:
    url: ssh://git@github.com/sample-accelerators/fragments
    ref:
      branch: feature/spring-boot-mysql
    subPath: spring-boot-mysql
    secretRef:
      name: vmware-jaret-credentials
